# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EraOfBand_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for EraOfBand_iOS
  pod 'KakaoSDK'
  pod 'Tabman', '~> 2.12'
  pod 'KeychainSwift', '~> 20.0'

end
